apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/jetstack/cert-manager/releases/download/v1.5.4/cert-manager.yaml
  - example-clusterissuer.yaml
  - letsencrypt-production-clusterissuer.yaml
